### ISSUE TITLE
Doesn t work

### ISSUE THREAD

**Issue by ebouda33** [chrisgavin/cheeky_acd_cli#1]
You have the same probleme .

it doesn't work 
and you have a bug for the filename README.rst it doesn t exist

**Comment by chrisgavin** [comment]
I changed it to a markdown file, and it's working for me. Screenshot from just now:

![image](https://cloud.githubusercontent.com/assets/5584439/26819155/98b2f258-4a95-11e7-9989-ab5c2930e6a8.png)

**Comment by ebouda33** [comment]
i follow your explain and when i execute pip install "git+https://github.com/chrisgavin/cheeky_acd_cli.git"
that crash

how know i use your acdcli ?

**Comment by chrisgavin** [comment]
Please clarify what you mean by "that crash". Do you have a stacktrace?

**Comment by ebouda33** [comment]
When i install : 

Collecting git+https://github.com/chrisgavin/cheeky_acd_cli.git
  Cloning https://github.com/chrisgavin/cheeky_acd_cli.git to /tmp/pip-lh3qpehb-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-lh3qpehb-build/setup.py", line 33, in <module>
        long_description=re.sub(repl[0], repl[1], read('README.rst')),
      File "/tmp/pip-lh3qpehb-build/setup.py", line 10, in read
        return open(os.path.join(os.path.dirname(__file__), fname), encoding='utf-8').read()
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-lh3qpehb-build/README.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-lh3qpehb-build/

i make it manually build and install
with rename the Readme.rst to read.md

**Comment by chrisgavin** [comment]
Ah, okay. I didn't realize that file was actually used as part of the build.

**Comment by chrisgavin** [comment]
I've now removed that dependency. Thanks.
